### ISSUE TITLE
Compatibility with TTT2

### ISSUE THREAD

**Issue by Alf21** [Exho1/TTT-ScoreboardTagging#1]
Could you make a suggestion of this modification to TTT2 (https://github.com/Alf21/TTT2) ? Or could I use it directly in TTT2?

**Comment by Exho1** [comment]
Sure feel free to use it in TTT2, just credit me somewhere in there and I'm cool with it. You'd know that codebase better and be able to test its functionality

**Comment by Alf21** [comment]
Okay thanks! And yea, sure, I will credit you :)
